<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>4fd59b0c-9bca-48d0-b2f1-3d3e047cee28</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="10.0.0" />
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" Version="1.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.10.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuickCart.Application\QuickCart.Application.csproj" />
    <ProjectReference Include="..\QuickCart.Contracts\QuickCart.Contracts.csproj" />
    <ProjectReference Include="..\QuickCart.Infrastructure\QuickCart.Infrastructure.csproj" />
  </ItemGroup>

</Project>
